{
 "title": "How wrong is forecast",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Capture completeness(TenneT uptime)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    price_period_start AS time,\r\n    count(*) / 75.0 AS \"Capture completeness\"\r\nFROM marts.fct_imbalance_spread\r\nWHERE $__timeFilter(price_period_start)\r\nGROUP BY price_period_start\r\nORDER BY price_period_start"
    }
   ]
  },
  {
   "title": "Negative day-ahead prices by hour ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    dutch_hour::text AS \"Hour\",\r\n    count(*) FILTER (WHERE is_negative_price) AS \"Negative slots\"\r\nFROM marts.fct_day_ahead_price\r\nGROUP BY dutch_hour\r\nORDER BY dutch_hour"
    }
   ]
  },
  {
   "title": "The duck curve",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    dutch_hour::text AS \"Hour\",\r\n    round(max(mean_price_eur_mwh) FILTER (WHERE NOT is_weekend), 2) AS \"Weekday\",\r\n    round(max(mean_price_eur_mwh) FILTER (WHERE is_weekend), 2)     AS \"Weekend\"\r\nFROM marts.agg_day_ahead_price_hourly\r\nGROUP BY dutch_hour\r\nORDER BY dutch_hour"
    }
   ]
  },
  {
   "title": "Forecast error by hour of day",
   "type": "barchart",
   "description": "This finding disproved the ramp hypothesis ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select \r\n       dutch_hour::text as \"Hour\",\r\n       round(avg(abs_spread_eur_mwh),2) as \"Average absolute spread\"\r\nFROM marts.fct_imbalance_spread\r\nwhere not has_imputed_input\r\ngroup by dutch_hour\r\norder by dutch_hour\r\n"
    }
   ]
  },
  {
   "title": "Spread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select \r\n       interval_start as time,\r\n       spread_eur_mwh as \"Spread\"\r\n       from marts.fct_imbalance_spread\r\n       where $__timeFilter(interval_start) \r\n       and not has_imputed_input\r\norder by interval_start"
    }
   ]
  },
  {
   "title": "Imbalance price vs day-ahead forecast",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select \r\n       interval_start as time,\r\n       imbalance_mid_price_eur_mwh as \"Imbalance price\",\r\n       day_ahead_price_eur_mwh as \"Day-ahead price\" \r\nFROM  marts.fct_imbalance_spread\r\nwhere $__timeFilter(interval_start) \r\nand not has_imputed_input\r\norder by interval_start \r\n"
    }
   ]
  }
 ]
}